### ISSUE TITLE
Move /dehydrated into $CERTS

### ISSUE THREAD

**Issue by jjakob** [schnatterer/letsencrypt-tomcat#2]
It would be good to move /dehydrated (where accounts are stored) into $CERTS so that accounts will also be stored in the docker volume. Otherwise storing just the certificates outside the container does not do you much good if the account is deleted if you recreate the container.
I did this in my Dockerfile:

```
RUN rm -rf /dehydrated
RUN ln -s /certs/dehydrated /dehydrated
```
I think the entrypoint script also needs to be updated to create the directory the symlink points to, otherwise writing to /dehydrated may fail. I created it with mkdir by hand in the volume.
It may be even better to set `BASEDIR="$CERTS"` in /etc/dehydrated/config.

**Comment by schnatterer** [comment]
Hey @jjakob, Thanks for sharing your findings.
Does this issue really belong in this repo or might it be for [schnatterer/letsencrypt-tomcat](https://github.com/schnatterer/letsencrypt-tomcat)? If so, I'd move the issue.
Would you be open for creating a PR? This would make the discussion much more expressive.

**Comment by jjakob** [comment]
Yes, it's not at the right place. I will open a PR on letsencrypt-tomcat after trying the BASEDIR change and getting it to a state that I like.
